// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Chromecast.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Grayjay.ClientServer.Protobuffers {

  /// <summary>Holder for reflection information generated from Chromecast.proto</summary>
  public static partial class ChromecastReflection {

    #region Descriptor
    /// <summary>File descriptor for Chromecast.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChromecastReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBDaHJvbWVjYXN0LnByb3RvIqsCCgtDYXN0TWVzc2FnZRI2ChBwcm90b2Nv",
            "bF92ZXJzaW9uGAEgAigOMhwuQ2FzdE1lc3NhZ2UuUHJvdG9jb2xWZXJzaW9u",
            "EhEKCXNvdXJjZV9pZBgCIAIoCRIWCg5kZXN0aW5hdGlvbl9pZBgDIAIoCRIR",
            "CgluYW1lc3BhY2UYBCACKAkSLgoMcGF5bG9hZF90eXBlGAUgAigOMhguQ2Fz",
            "dE1lc3NhZ2UuUGF5bG9hZFR5cGUSFAoMcGF5bG9hZF91dGY4GAYgASgJEhYK",
            "DnBheWxvYWRfYmluYXJ5GAcgASgMIiEKD1Byb3RvY29sVmVyc2lvbhIOCgpD",
            "QVNUVjJfMV8wEAAiJQoLUGF5bG9hZFR5cGUSCgoGU1RSSU5HEAASCgoGQklO",
            "QVJZEAFCJkgDqgIhR3JheWpheS5DbGllbnRTZXJ2ZXIuUHJvdG9idWZmZXJz"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Grayjay.ClientServer.Protobuffers.CastMessage), global::Grayjay.ClientServer.Protobuffers.CastMessage.Parser, new[]{ "ProtocolVersion", "SourceId", "DestinationId", "Namespace", "PayloadType", "PayloadUtf8", "PayloadBinary" }, null, new[]{ typeof(global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.ProtocolVersion), typeof(global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.PayloadType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CastMessage : pb::IMessage<CastMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CastMessage> _parser = new pb::MessageParser<CastMessage>(() => new CastMessage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CastMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grayjay.ClientServer.Protobuffers.ChromecastReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CastMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CastMessage(CastMessage other) : this() {
      _hasBits0 = other._hasBits0;
      protocolVersion_ = other.protocolVersion_;
      sourceId_ = other.sourceId_;
      destinationId_ = other.destinationId_;
      namespace_ = other.namespace_;
      payloadType_ = other.payloadType_;
      payloadUtf8_ = other.payloadUtf8_;
      payloadBinary_ = other.payloadBinary_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CastMessage Clone() {
      return new CastMessage(this);
    }

    /// <summary>Field number for the "protocol_version" field.</summary>
    public const int ProtocolVersionFieldNumber = 1;
    private readonly static global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.ProtocolVersion ProtocolVersionDefaultValue = global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.ProtocolVersion.Castv210;

    private global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.ProtocolVersion protocolVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.ProtocolVersion ProtocolVersion {
      get { if ((_hasBits0 & 1) != 0) { return protocolVersion_; } else { return ProtocolVersionDefaultValue; } }
      set {
        _hasBits0 |= 1;
        protocolVersion_ = value;
      }
    }
    /// <summary>Gets whether the "protocol_version" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasProtocolVersion {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "protocol_version" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearProtocolVersion() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "source_id" field.</summary>
    public const int SourceIdFieldNumber = 2;
    private readonly static string SourceIdDefaultValue = "";

    private string sourceId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SourceId {
      get { return sourceId_ ?? SourceIdDefaultValue; }
      set {
        sourceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "source_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSourceId {
      get { return sourceId_ != null; }
    }
    /// <summary>Clears the value of the "source_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSourceId() {
      sourceId_ = null;
    }

    /// <summary>Field number for the "destination_id" field.</summary>
    public const int DestinationIdFieldNumber = 3;
    private readonly static string DestinationIdDefaultValue = "";

    private string destinationId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DestinationId {
      get { return destinationId_ ?? DestinationIdDefaultValue; }
      set {
        destinationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "destination_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDestinationId {
      get { return destinationId_ != null; }
    }
    /// <summary>Clears the value of the "destination_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDestinationId() {
      destinationId_ = null;
    }

    /// <summary>Field number for the "namespace" field.</summary>
    public const int NamespaceFieldNumber = 4;
    private readonly static string NamespaceDefaultValue = "";

    private string namespace_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Namespace {
      get { return namespace_ ?? NamespaceDefaultValue; }
      set {
        namespace_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "namespace" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNamespace {
      get { return namespace_ != null; }
    }
    /// <summary>Clears the value of the "namespace" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNamespace() {
      namespace_ = null;
    }

    /// <summary>Field number for the "payload_type" field.</summary>
    public const int PayloadTypeFieldNumber = 5;
    private readonly static global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.PayloadType PayloadTypeDefaultValue = global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.PayloadType.String;

    private global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.PayloadType payloadType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.PayloadType PayloadType {
      get { if ((_hasBits0 & 2) != 0) { return payloadType_; } else { return PayloadTypeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        payloadType_ = value;
      }
    }
    /// <summary>Gets whether the "payload_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPayloadType {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "payload_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayloadType() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "payload_utf8" field.</summary>
    public const int PayloadUtf8FieldNumber = 6;
    private readonly static string PayloadUtf8DefaultValue = "";

    private string payloadUtf8_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PayloadUtf8 {
      get { return payloadUtf8_ ?? PayloadUtf8DefaultValue; }
      set {
        payloadUtf8_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "payload_utf8" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPayloadUtf8 {
      get { return payloadUtf8_ != null; }
    }
    /// <summary>Clears the value of the "payload_utf8" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayloadUtf8() {
      payloadUtf8_ = null;
    }

    /// <summary>Field number for the "payload_binary" field.</summary>
    public const int PayloadBinaryFieldNumber = 7;
    private readonly static pb::ByteString PayloadBinaryDefaultValue = pb::ByteString.Empty;

    private pb::ByteString payloadBinary_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString PayloadBinary {
      get { return payloadBinary_ ?? PayloadBinaryDefaultValue; }
      set {
        payloadBinary_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "payload_binary" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPayloadBinary {
      get { return payloadBinary_ != null; }
    }
    /// <summary>Clears the value of the "payload_binary" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayloadBinary() {
      payloadBinary_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CastMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CastMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProtocolVersion != other.ProtocolVersion) return false;
      if (SourceId != other.SourceId) return false;
      if (DestinationId != other.DestinationId) return false;
      if (Namespace != other.Namespace) return false;
      if (PayloadType != other.PayloadType) return false;
      if (PayloadUtf8 != other.PayloadUtf8) return false;
      if (PayloadBinary != other.PayloadBinary) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasProtocolVersion) hash ^= ProtocolVersion.GetHashCode();
      if (HasSourceId) hash ^= SourceId.GetHashCode();
      if (HasDestinationId) hash ^= DestinationId.GetHashCode();
      if (HasNamespace) hash ^= Namespace.GetHashCode();
      if (HasPayloadType) hash ^= PayloadType.GetHashCode();
      if (HasPayloadUtf8) hash ^= PayloadUtf8.GetHashCode();
      if (HasPayloadBinary) hash ^= PayloadBinary.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasProtocolVersion) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ProtocolVersion);
      }
      if (HasSourceId) {
        output.WriteRawTag(18);
        output.WriteString(SourceId);
      }
      if (HasDestinationId) {
        output.WriteRawTag(26);
        output.WriteString(DestinationId);
      }
      if (HasNamespace) {
        output.WriteRawTag(34);
        output.WriteString(Namespace);
      }
      if (HasPayloadType) {
        output.WriteRawTag(40);
        output.WriteEnum((int) PayloadType);
      }
      if (HasPayloadUtf8) {
        output.WriteRawTag(50);
        output.WriteString(PayloadUtf8);
      }
      if (HasPayloadBinary) {
        output.WriteRawTag(58);
        output.WriteBytes(PayloadBinary);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasProtocolVersion) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ProtocolVersion);
      }
      if (HasSourceId) {
        output.WriteRawTag(18);
        output.WriteString(SourceId);
      }
      if (HasDestinationId) {
        output.WriteRawTag(26);
        output.WriteString(DestinationId);
      }
      if (HasNamespace) {
        output.WriteRawTag(34);
        output.WriteString(Namespace);
      }
      if (HasPayloadType) {
        output.WriteRawTag(40);
        output.WriteEnum((int) PayloadType);
      }
      if (HasPayloadUtf8) {
        output.WriteRawTag(50);
        output.WriteString(PayloadUtf8);
      }
      if (HasPayloadBinary) {
        output.WriteRawTag(58);
        output.WriteBytes(PayloadBinary);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasProtocolVersion) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ProtocolVersion);
      }
      if (HasSourceId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SourceId);
      }
      if (HasDestinationId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DestinationId);
      }
      if (HasNamespace) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Namespace);
      }
      if (HasPayloadType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PayloadType);
      }
      if (HasPayloadUtf8) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PayloadUtf8);
      }
      if (HasPayloadBinary) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(PayloadBinary);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CastMessage other) {
      if (other == null) {
        return;
      }
      if (other.HasProtocolVersion) {
        ProtocolVersion = other.ProtocolVersion;
      }
      if (other.HasSourceId) {
        SourceId = other.SourceId;
      }
      if (other.HasDestinationId) {
        DestinationId = other.DestinationId;
      }
      if (other.HasNamespace) {
        Namespace = other.Namespace;
      }
      if (other.HasPayloadType) {
        PayloadType = other.PayloadType;
      }
      if (other.HasPayloadUtf8) {
        PayloadUtf8 = other.PayloadUtf8;
      }
      if (other.HasPayloadBinary) {
        PayloadBinary = other.PayloadBinary;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProtocolVersion = (global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.ProtocolVersion) input.ReadEnum();
            break;
          }
          case 18: {
            SourceId = input.ReadString();
            break;
          }
          case 26: {
            DestinationId = input.ReadString();
            break;
          }
          case 34: {
            Namespace = input.ReadString();
            break;
          }
          case 40: {
            PayloadType = (global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.PayloadType) input.ReadEnum();
            break;
          }
          case 50: {
            PayloadUtf8 = input.ReadString();
            break;
          }
          case 58: {
            PayloadBinary = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProtocolVersion = (global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.ProtocolVersion) input.ReadEnum();
            break;
          }
          case 18: {
            SourceId = input.ReadString();
            break;
          }
          case 26: {
            DestinationId = input.ReadString();
            break;
          }
          case 34: {
            Namespace = input.ReadString();
            break;
          }
          case 40: {
            PayloadType = (global::Grayjay.ClientServer.Protobuffers.CastMessage.Types.PayloadType) input.ReadEnum();
            break;
          }
          case 50: {
            PayloadUtf8 = input.ReadString();
            break;
          }
          case 58: {
            PayloadBinary = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CastMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ProtocolVersion {
        [pbr::OriginalName("CASTV2_1_0")] Castv210 = 0,
      }

      public enum PayloadType {
        [pbr::OriginalName("STRING")] String = 0,
        [pbr::OriginalName("BINARY")] Binary = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
